"""City readiness briefing (CR-018): deterministic, no LLM, fast.

Built from cache/{slug}/result.json + city.json + crashes.json (+ ai_summary.md if present).
Stamped with the data date and the model artifact commit rather than "now", so rebuilding
from the same inputs gives the same file.
"""
from __future__ import annotations

import functools
import json
import logging
import subprocess

import h3

from app import cache
from app.schemas import REFERENCE_LABEL

log = logging.getLogger(__name__)

TITLE = "City readiness briefing: candidate test plan from public data"
DISCLAIMER = (
    "Generated by CityShift from public data. It ranks where this city's driving environment "
    f"differs from {REFERENCE_LABEL} and proposes candidate test scenarios. It does not train "
    "Waymo's models or describe Waymo's internal systems. Red means unfamiliar to the car, not dangerous."
)
SOURCES = [
    {"name": "OpenStreetMap via OSMnx", "licence": "ODbL 1.0",
     "note": "roads, signals, crossings, transit, places"},
    {"name": "Open-Meteo Historical Weather API", "licence": "CC BY 4.0",
     "note": "daily precipitation and snowfall, 2020-2024"},
    {"name": "Copernicus DEM GLO-90 via Open-Meteo", "licence": "Copernicus DEM licence (free use with attribution)",
     "note": "terrain slope; collected but not scored"},
    {"name": "NHTSA FARS", "licence": "US public domain",
     "note": "fatal crashes 2020-2024 (2024 preliminary); US cities only"},
]
AI_LABEL = "AI-generated summary"
TOP_AREAS = 20
TOP_DIFFERENCES = 5
TOP_HOTSPOTS = 5
MD_HEX_LIST = 10


@functools.lru_cache(maxsize=1)
def _artifact() -> dict:
    """Commit of the saved reference artifact, its fit time, and the reference city names."""
    meta_path = cache.REPO_ROOT / "backend" / "app" / "model" / "reference" / "reference_meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.is_file() else {}
    try:
        commit = subprocess.run(
            ["git", "log", "-1", "--format=%h", "--", str(meta_path.with_name("phoenix_reference.joblib"))],
            capture_output=True, text=True, cwd=cache.REPO_ROOT, timeout=5,
        ).stdout.strip() or "unknown"
    except (OSError, subprocess.SubprocessError):
        commit = "unknown"
    names = []
    for slug in meta.get("reference_slugs", []):
        path = cache.city_dir(slug) / "city.json"
        names.append(json.loads(path.read_text(encoding="utf-8"))["name"] if path.is_file() else slug)
    return {"commit": commit, "fit_timestamp": str(meta.get("fit_timestamp", "unknown")), "cities": names}


def _center(cell: str) -> dict:
    lat, lng = h3.cell_to_latlng(cell)
    return {"h3": cell, "lat": round(lat, 5), "lng": round(lng, 5)}


def _ratio(target: float, reference: float) -> float | None:
    return round(target / reference, 2) if reference else None


def _read_ai_summary(slug: str) -> dict | None:
    path = cache.city_dir(slug) / "ai_summary.md"
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8").strip()
    model = "unknown"
    if text.startswith("<!-- model:"):
        first, _, text = text.partition("\n")
        model = first.removeprefix("<!-- model:").removesuffix("-->").strip()
    return {"label": AI_LABEL, "text": text.strip(), "model": model}


def build_briefing(slug: str) -> dict:
    """The briefing as a dict. Raises FileNotFoundError when the city has no result.json."""
    result = cache.read_json(slug, "result.json")
    city = cache.read_json(slug, "city.json")
    crashes_path = cache.city_dir(slug) / "crashes.json"
    crashes = json.loads(crashes_path.read_text(encoding="utf-8")) if crashes_path.is_file() else None
    summary, hexes = result["summary"], result["hexes"]
    crash_by_hex = crashes["by_hex"] if crashes and crashes.get("available") else None

    bands = {band: sum(h["band"] == band for h in hexes) for band in ("red", "yellow", "green")}
    diffs = []
    for row in summary["feature_comparison"]:
        if not row["target"] and not row["reference"]:
            continue
        diffs.append({**row, "ratio": _ratio(row["target"], row["reference"])})
    # Features the reference median lacks entirely sort first, then by ratio.
    diffs.sort(key=lambda r: (r["ratio"] is not None, -(r["ratio"] or 0), r["name"]))

    scenarios = [{
        "rank": rank,
        "id": s["id"],
        "title": s["title"],
        "priority": s["priority"],
        "scope": s["scope"],
        "description": s["description"],
        "triggered_by": s["triggered_by"],
        "n_hexes": len(s["hex_ids"]) if s["scope"] == "hex" else summary["n_hexes"],
        "hexes": [_center(cell) for cell in s["hex_ids"]],
    } for rank, s in enumerate(result["scenarios"], start=1)]

    ranked = sorted(hexes, key=lambda h: (-h["shift_score"], h["h3"]))[:TOP_AREAS]
    areas = [{
        "rank": rank,
        **_center(h["h3"]),
        "shift_score": h["shift_score"],
        "band": h["band"],
        "top_features": h["top_features"],
        "novel": h["novel"],
        "fatal_crashes": (crash_by_hex.get(h["h3"], {}).get("count", 0) if crash_by_hex is not None else None),
    } for rank, h in enumerate(ranked, start=1)]

    if crashes and crashes.get("available"):
        points, total = crashes["points"], crashes["total"]
        share = (lambda key: round(100.0 * sum(p[key] for p in points) / total, 1)) if total else (lambda key: 0.0)
        hot = sorted(crashes["by_hex"].items(), key=lambda kv: (-kv[1]["count"], kv[0]))[:TOP_HOTSPOTS]
        crash_context = {
            "available": True, "source": crashes["source"], "note": crashes["note"],
            "years": crashes["years"], "preliminary_years": crashes["preliminary_years"],
            "total": total, "pct_pedestrian": share("pedestrian"), "pct_cyclist": share("cyclist"),
            "pct_dark": share("dark"),
            "hotspots": [{**_center(cell), "count": v["count"], "pct": v["pct"]} for cell, v in hot],
        }
    else:
        crash_context = {"available": False,
                         "reason": crashes.get("reason", "no crash data") if crashes else "no crash data"}

    artifact = _artifact()
    return {
        "title": TITLE,
        "disclaimer": DISCLAIMER,
        "city": {"name": city["name"], "slug": slug, "center": summary["center"],
                 "radius_km": summary["radius_km"], "data_as_of": city["created_at"][:10]},
        "reference": {"label": REFERENCE_LABEL, "cities": artifact["cities"],
                      "model_artifact": {"commit": artifact["commit"], "fit_timestamp": artifact["fit_timestamp"]}},
        "sources": SOURCES,
        "ai_summary": _read_ai_summary(slug),
        "key_numbers": {
            "pct_red": summary["pct_red"], "n_hexes": summary["n_hexes"], "bands": bands,
            "climate": {"target": summary["climate"]["target"], "reference_max": summary["climate"]["reference"]},
            "driving_side": summary["driving_side"], "osm_completeness": summary["osm_completeness"],
            "novel_city": summary["novel_city"],
        },
        "biggest_differences": diffs[:TOP_DIFFERENCES],
        "scenarios": scenarios,
        "unfamiliar_areas": areas,
        "crash_context": crash_context,
        "limitations": [
            "Crash data is NHTSA FARS: fatal crashes only, US cities only, 2024 preliminary. "
            "Counts are compared within a city, never across cities.",
            "Terrain slope is collected but not scored: the 90 m Copernicus surface model reads tall "
            "buildings as slope.",
            f"OpenStreetMap completeness varies by city; here {summary['osm_completeness']:.0%} of road "
            "segments carry a speed limit or lane count.",
            "CityShift measures infrastructure and climate from public data, not driver behaviour or "
            "traffic volumes.",
            f"Scores are relative to {REFERENCE_LABEL}, pooled; red means unfamiliar, not dangerous.",
        ],
    }


def _fmt_feature(f: dict) -> str:
    return f"{f['name']} {f['value']:g} (reference median {f['ref_median']:g}, z {f['z']:+.1f}, {f['pct']:g}th pct)"


def render_markdown(b: dict) -> str:
    k, c = b["key_numbers"], b["city"]
    clim_t, clim_r = k["climate"]["target"], k["climate"]["reference_max"]
    out = [
        f"# {b['title']}",
        f"## {c['name']}",
        "",
        f"_{b['disclaimer']}_",
        "",
        f"- Data as of: {c['data_as_of']} · area: {c['radius_km']:g} km radius around "
        f"{c['center']['lat']:.4f}, {c['center']['lng']:.4f}",
        f"- Reference: {b['reference']['label']} ({'; '.join(b['reference']['cities'])})",
        f"- Model artifact: commit {b['reference']['model_artifact']['commit']}, fitted "
        f"{b['reference']['model_artifact']['fit_timestamp'][:10]}",
        "- Sources: " + "; ".join(f"{s['name']} ({s['licence']})" for s in b["sources"]),
        "",
    ]
    if b["ai_summary"]:
        out += [f"## {b['ai_summary']['label']}", "", f"_Model: {b['ai_summary']['model']}. "
                "Grounded on this briefing's data; check numbers against the sections below._", "",
                b["ai_summary"]["text"], ""]
    out += [
        "## Key numbers", "",
        f"- Unfamiliar (red): {k['pct_red']:g}% of {k['n_hexes']} hexes "
        f"(red {k['bands']['red']}, yellow {k['bands']['yellow']}, green {k['bands']['green']})",
        f"- Rain days/year: {clim_t['rain_days_per_year']:g} (reference max {clim_r['rain_days_per_year']:g}); "
        f"heavy-rain days: {clim_t['heavy_rain_days_per_year']:g} (max {clim_r['heavy_rain_days_per_year']:g}); "
        f"snow days: {clim_t['snow_days_per_year']:g} (max {clim_r['snow_days_per_year']:g})",
        f"- Driving side: {k['driving_side']}",
        f"- OSM completeness: {k['osm_completeness']:.0%}",
        f"- City-level novel flags: {', '.join(k['novel_city']) or 'none'}",
        "", "## Biggest differences vs reference (medians per hex)", "",
        "| Feature | This city | Reference | Ratio |", "|---|---:|---:|---:|",
    ]
    for d in b["biggest_differences"]:
        ratio = f"{d['ratio']:g}x" if d["ratio"] is not None else "new (reference 0)"
        out.append(f"| {d['name']} | {d['target']:g} | {d['reference']:g} | {ratio} |")
    out += ["", "## Prioritized test scenarios", ""]
    if not b["scenarios"]:
        out.append("No scenario rule fired for this city.")
    for s in b["scenarios"]:
        out += [f"### {s['rank']}. {s['title']}",
                f"- id `{s['id']}` · priority {s['priority']:g} · scope {s['scope']} · {s['n_hexes']} hexes",
                f"- Triggered by: {'; '.join(s['triggered_by'])}",
                f"- {s['description']}"]
        if s["hexes"]:
            listed = ", ".join(f"`{x['h3']}` ({x['lat']}, {x['lng']})" for x in s["hexes"][:MD_HEX_LIST])
            more = len(s["hexes"]) - MD_HEX_LIST
            out.append(f"- Hexes: {listed}" + (f", and {more} more (full list in briefing.json)" if more > 0 else ""))
        out.append("")
    out += [f"## Top {len(b['unfamiliar_areas'])} most unfamiliar areas", "",
            "| # | Hex | Lat, lng | Score | Top reasons | Novel | Fatal crashes |",
            "|---:|---|---|---:|---|---|---:|"]
    for a in b["unfamiliar_areas"]:
        reasons = "<br>".join(_fmt_feature(f) for f in a["top_features"])
        crashes = "n/a" if a["fatal_crashes"] is None else str(a["fatal_crashes"])
        out.append(f"| {a['rank']} | `{a['h3']}` | {a['lat']}, {a['lng']} | {a['shift_score']:g} | {reasons} "
                   f"| {', '.join(a['novel']) or '-'} | {crashes} |")
    cc = b["crash_context"]
    out += ["", "## Crash context", ""]
    if cc["available"]:
        out += [f"{cc['total']} fatal crashes in {cc['years'][0]}-{cc['years'][-1]} "
                f"({', '.join(map(str, cc['preliminary_years']))} preliminary), {cc['source']}. "
                f"{cc['pct_pedestrian']:g}% involved a pedestrian, {cc['pct_cyclist']:g}% a cyclist, "
                f"{cc['pct_dark']:g}% happened in the dark. Hotspots within this city:", "",
                "| Hex | Lat, lng | Fatal crashes | Within-city percentile |", "|---|---|---:|---:|"]
        out += [f"| `{h['h3']}` | {h['lat']}, {h['lng']} | {h['count']} | {h['pct']:g} |" for h in cc["hotspots"]]
    else:
        out.append(f"Not available: {cc['reason']}.")
    out += ["", "## Limitations", ""] + [f"- {item}" for item in b["limitations"]] + [""]
    return "\n".join(out)


def write_briefing(slug: str) -> dict:
    """Write cache/{slug}/briefing.json and briefing.md; returns the briefing dict."""
    briefing = build_briefing(slug)
    cache.write_json(slug, "briefing.json", briefing)
    path = cache.city_dir(slug) / "briefing.md"
    tmp = path.with_suffix(".md.tmp")
    tmp.write_text(render_markdown(briefing), encoding="utf-8")
    tmp.replace(path)
    return briefing
